apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: etcd-metrics-proxy
resources:
- rbac.yaml
- rbac-client.yaml
- serviceaccount.yaml
- service.yaml
- daemonset.yaml
- servicemonitor.yaml
